### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by NekoMazix** [json1c/telegram-raid-botnet#1]
![image](https://user-images.githubusercontent.com/86486680/140576193-111d00c0-5134-4c64-b0b8-4f81dfd96804.png)

**Comment by json1c** [comment]
конфиг покажи

**Comment by json1c** [comment]
@json1c .

**Comment by json1c** [comment]
@NekoMazix Конфиг покажи

**Comment by NekoMazix** [comment]
> @NekoMazix Конфиг покажи

что в нем быть вообще должно? я не понимаю

**Comment by KrasProject-2021** [comment]
@NekoMazix Конфиги должны быть

**Comment by json1c** [comment]
@NekoMazix При первом запуске ботнета тебе должно задать несколько вопросов, после этого появится файл config.toml

**Comment by FlingerXD** [comment]
Щас бы хуйца пососат смачного..

**Comment by FlingerXD** [comment]
@FlingerXD ой

**Comment by json1c** [comment]
@FlingerXD Бери

**Comment by FlingerXD** [comment]
@json1c با سلام

خیلی خوش آمدید

⚡️ جهت عضویت در کانال تقویم اسلام ابتدا روی لینک آبی رنگ زیر کلیک کنید و سپس گزینه ی جوین یا همان پیوستن را بزنید

✅ کانال تقویم اسلام 👇

**Comment by json1c** [comment]
@FlingerXD Зачем

**Comment by lkqas** [comment]
@FlingerXD Ок

**Comment by wannatermux** [comment]
@FlingerXD арабы

**Comment by zxcgloomed** [comment]
бля почему конфиг не создается, я запускаю main.py и вообще нихуя

**Comment by lkqas** [comment]
@zxcgloomed ХАХАХАХАХАХ

**Comment by 4burek228** [comment]
@zxcgloomed АХАХАХАХ

**Comment by json1c** [comment]
@zxcgloomed Приложи скрин ошибки в ответе

**Comment by StrikcYT** [comment]
ليس لدي أي منهما config.toml
