### ISSUE TITLE
botnet startup problem

### ISSUE THREAD

**Issue by Ripozero** [json1c/telegram-raid-botnet#3]
![Screenshot_20220218-232239_Termux_1](https://user-images.githubusercontent.com/90804801/154758267-e5607cdc-4e29-4abc-98e0-7b69b4d3b303.png)
![Screenshot_20220218-232350_Termux_1](https://user-images.githubusercontent.com/90804801/154758276-b1d3c114-c375-4dc2-b96e-fd78a01c491a.png)

**Comment by lkqas** [comment]
Попробуй откатить питон до 3.9

**Comment by SsNiPeR1** [comment]
> Попробуй откатить питон до 3.9

думаю английский он не знает

**Comment by SsNiPeR1** [comment]
> ![Screenshot_20220218-232239_Termux_1](https://user-images.githubusercontent.com/90804801/154758267-e5607cdc-4e29-4abc-98e0-7b69b4d3b303.png) ![Screenshot_20220218-232350_Termux_1](https://user-images.githubusercontent.com/90804801/154758276-b1d3c114-c375-4dc2-b96e-fd78a01c491a.png)

try to downgrade python to version <= 3.9

**Comment by lilwonka** [comment]
@SsNiPeR1 touch modules/__init__.py

**Comment by lilwonka** [comment]
@lilwonka сука не туда

**Comment by SsNiPeR1** [comment]
@lilwonka

**Comment by Adbdaziz** [comment]
Кто это

сб, 12 мар. 2022 г., 01:10 SsNiPeR1 ***@***.***>:
